# CodingBat

## Wramup1

**sleep_in**:
    
    The parameter weekday is True if it is a weekday, and the parameter vacation is True if we are on vacation. We sleep in if it is not a weekday or we're on vacation. Return True if we sleep in.



In [1]:
def sleep_in(weekday, vacation):
    if weekday == False or vacation ==True:
        return True
    else:
        return False


In [2]:
sleep_in(False,False)

True

**monkey_trouble** :

    We have two monkeys, a and b, and the parameters a_smile and b_smile indicate if each is smiling. We are in trouble if they are both smiling or if neither of them is smiling. Return True if we are in trouble.

In [3]:
def monkey_trouble(a_smile, b_smile):
    if ((a_smile and b_smile) or (not a_smile and not b_smile )):
        return True
    else:
        return False
  


In [4]:
monkey_trouble(True, True) 

True

In [5]:
monkey_trouble(True, False)

False

**sum_double**:

    Given two int values, return their sum. Unless the two values are the same, then return double their sum.



In [6]:
def sum_double(a, b):
    if a==b:
        return 2*(a+b)
    else:
        return a+b

In [7]:
sum_double(3, 3)

12

In [8]:
sum_double(-1, 0)

-1

**diff21**:

    Given an int n, return the absolute difference between n and 21, except return double the absolute difference if n is over 21.




In [9]:
def diff21(n):
    if n<=21:
        return 21-n
    else:
        return 2*(n-21)


In [10]:
diff21(19)

2

In [11]:
diff21(26)

10

**parrot_trouble**:

    We have a loud talking parrot. The "hour" parameter is the current hour time in the range 0..23. We are in trouble if the parrot is talking and the hour is before 7 or after 20. Return True if we are in trouble.




In [12]:
def parrot_trouble(talking, hour):
    if talking and (hour<7 or hour>20):
        return True
    else:
        return False


In [13]:
parrot_trouble(True, 6)

True

In [14]:
parrot_trouble(True, 7)

False

**makes10**:

    Given 2 ints, a and b, return True if one if them is 10 or if their sum is 10.




In [15]:
def makes10(a, b):
    if a==10 or b==10 or a+b==10:
        return True
    else:
        return False


In [16]:
makes10(9, 10)

True

In [17]:
makes10(9, 1)

True

**near_hundred**:

    Given an int n, return True if it is within 10 of 100 or 200. Note: abs(num) computes the absolute value of a number.



In [18]:
def near_hundred(n):
    x = abs(100-n)
    y = abs(200-n)
    if (x<=10 or y<=10):
        return True
    else:
        return False

In [19]:
near_hundred(93)

True

In [20]:
near_hundred(89)

False

**pos_neg**:

    Given 2 int values, return True if one is negative and one is positive. Except if the parameter "negative" is True, then return True only if both are negative.


In [21]:
def pos_neg(a, b, negative):
    if ((a<0 and b>0) or (a>0 and b<0)) and not negative :
        return True
    elif a<0 and b<0 and negative:
        return True
    else:
        return False

In [22]:
pos_neg(1, -1, False)

True

In [23]:
pos_neg(-1, 1, True)

False

In [24]:
pos_neg(-4, -5, True) 

True

**not_string**:

    Given a string, return a new string where "not " has been added to the front. However, if the string already begins with "not", return the string unchanged.



In [25]:
def not_string(str):
    s = "not "
    list1 = str.split()
    if list1[0] == "not":
        return str
    else:
        s+=str
        return s

In [26]:
not_string('candy')

'not candy'

In [27]:
not_string('not bad')

'not bad'

**missing_char**:

    Given a non-empty string and an int n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive).





In [28]:
def missing_char(str, n):
    x = str[n]
    s = ""
    for i in str:
        if i==x:
            continue
        else:
            s+=i
    return s

In [29]:
missing_char('kitten', 0)

'itten'

**front_back**:

    Given a string, return a new string where the first and last chars have been exchanged.






In [30]:
def front_back(str):
    if len(str)==1:
        return str
    else:
        s = ""
        s+=str[len(str)-1]
        s+=str[1:len(str)-1]
        s+=str[0]
    return s



In [31]:
front_back('rahma')

'aahmr'

In [32]:
front_back('a')

'a'

In [33]:
front_back('ab') 

'ba'

In [34]:
front_back('aavj')

'java'

**front3**:

` Given a string, we'll say that the front is the first 3 chars of the string. If the string length is less than 3, the front is whatever is there. Return a new string which is 3 copies of the front.







In [35]:
def front3(str):
    s = ""
    if len(str)>=3:
        s = str[0]+str[1]+str[2]
        return s*3
    else:
        return str*3
        

In [36]:
front3('Java') 

'JavJavJav'

In [37]:
front3('Chocolate')

'ChoChoCho'

In [38]:
front3('abc')

'abcabcabc'

## Wramup2

**string_times**:

` Given a string and a non-negative int n, return a larger string that is n copies of the original string.









In [39]:
def string_times(str, n):
    s = str*n
    return s


In [40]:
string_times('Hi', 2)

'HiHi'

**front_times**:

    Given a string and a non-negative int n, we'll say that the front of the string is the first 3 chars, or whatever is there if the string is less than length 3. Return n copies of the front;






In [41]:
def front_times(str, n):
    s = ""
    if len(str)>=3:
        s = str[0]+str[1]+str[2]
        return s*n
    else:
        return str*n

In [42]:
front_times('Chocolate', 2)

'ChoCho'

In [43]:
front_times('Chocolate', 3)

'ChoChoCho'

**string_bits**:

    Given a string, return a new string made of every other char starting with the first, so "Hello" yields "Hlo".




In [44]:
def string_bits(str):
    s = str[::2]
    return s


In [45]:
string_bits('Hello')

'Hlo'

In [46]:
string_bits('Heeololeo')

'Hello'

**string_splosion**:

    Given a non-empty string like "Code" return a string like "CCoCodCode".





In [47]:
def string_splosion(str):
    s=""
    x = 1
    for i in range(0,len(str)):
        for j in range(0,i+1):
            s+=str[j]
        j=0
    return s
                           
        

In [48]:
string_splosion('Code') 

'CCoCodCode'

**last2**:

    Given a string, return the count of the number of times that a substring length 2 appears in the string and also as the last 2 chars of the string, so "hixxxhi" yields 1 (we won't count the end substring).





In [49]:
def last2(str):
    n = len(str)-1
    Count = 0 
    for i in range(0,len(str)-2):
        if str[i]==str[n-1] and str[i+1]==str[n]:
            Count+=1
    return Count
        


In [50]:
last2('hixxhi') 

1

In [51]:
last2('xaxxaxaxx') 

1

In [52]:
last2('axxxaaxx')

2

**array_count9**:

    Given an array of ints, return the number of 9's in the array.





In [53]:
def array_count9(nums):
    count = 0
    for i in nums:
        if i==9:
            count+=1
    return count

In [54]:
array_count9([1, 9, 9])

2

**array_front9**:

    Given an array of ints, return True if one of the first 4 elements in the array is a 9. The array length may be less than 4.






In [55]:
def array_front9(nums):
    flag = False
    if len(nums)>4:
        for i in range(0,4):
            if nums[i]==9:
                flag = True
    else:
        for i in nums:
            if i==9:
                flag=True
    return flag    

In [56]:
array_front9([1, 2, 9, 3, 4])

True

In [57]:
array_front9([1, 2, 3, 4, 9])

False

In [58]:
array_front9([1, 2, 3, 4, 5])

False

**array123**:

    Given an array of ints, return True if the sequence of numbers 1, 2, 3 appears in the array somewhere.






In [59]:
def array123(nums):
    flag = False
    for i in range(0,len(nums)-2):
        if nums[i]==1 and nums[i+1]==2 and nums[i+2]==3:
            flag = True
            break
    return flag
            

In [60]:
array123([1, 1, 2, 1, 1]) 

False

In [61]:
array123([1, 1, 2, 1, 2, 3])

True

**string_match**:

    Given 2 strings, a and b, return the number of the positions where they contain the same length 2 substring. So "xxcaazz" and "xxbaaz" yields 3, since the "xx", "aa", and "az" substrings appear in the same place in both strings.



In [62]:
def string_match(a, b):
    count = 0
    x = min(len(a),len(b))
    for i in range(0,x-1):
        if a[i]==b[i] and a[i+1]==b[i+1]:
            count+=1
    return count


In [63]:
string_match('xxcaazz', 'xxbaaz')

3

In [64]:
string_match('abc', 'abc')

2

In [65]:
string_match('abc', 'axc')

0

# Hacker Rank

**Arrays**:

    You are given a space separated list of numbers.
    Your task is to print a reversed NumPy array with the element type float.


In [66]:
import numpy as np

In [67]:
def arrays(arr):
    arr = np.array(arr,float)
    arr = arr[::-1]
    return arr

In [68]:
arrays([1,2,3,4])

array([4., 3., 2., 1.])

**Shape and Reshape**:
    
    You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [69]:
import numpy as np

In [70]:
def my_array(arr):
    arr = np.array(arr)
    arr = arr.reshape(3,3)
    return arr

In [71]:
my_array([1,2,3,4,5,6,7,8,9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Transpose and Flatten**:

    You are given a N X M integer array matrix with space separated elements ( N= rows and  M= columns).
    Your task is to print the transpose and flatten results.

In [72]:
import numpy as np
arr = []
N = int(input("your rows "))
M = int(input("yor coloumns "))
for i in range(N):
    a =[] 
    for j in range(M):
         a.append(int(input())) 
    arr.append(a) 
arr = np.array(arr)
print (np.transpose(arr))
print (arr.flatten())


your rows 2
yor coloumns 2
1
2
3
4
[[1 3]
 [2 4]]
[1 2 3 4]


**Concatenate**:

    You are given two integer arrays of size N X P and M X P (N & M are rows, P and  is the column). Your task is to concatenate the arrays along axis 0.

In [73]:
import numpy as np
arr = []
arr2 = []
N = int(input("your array one rows "))
M = int(input("yor array two rows "))
P = int(input("yor array coloumns "))
print("your first array is ")
for i in range(N):
    a =[] 
    for j in range(P):
         a.append(int(input())) 
    arr.append(a) 
print("your second array is ")
for i in range(M):
    b =[] 
    for j in range(P):
         b.append(int(input())) 
    arr2.append(b) 
arr = np.array(arr)
arr2 = np.array(arr2)
print (np.concatenate((arr,arr2), axis = 0) )

your array one rows 4
yor array two rows 3
yor array coloumns 2
your first array is 
1
2
1
2
1
2
1
2
your second array is 
3
2
3
2
3
2
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 2]
 [3 2]
 [3 2]]


**Zeros and Ones**:

    You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.



In [77]:
R = int(input("your rows "))
C = int(input("your coloumns "))
x = int(input("your repetition "))
for i in range(x):
    print(np.zeros((R,C),dtype = np.int))
for i in range(x):
    print(np.ones((R,C),dtype = np.int))


3
3
3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


**Eye and Identity**:

    Your task is to print an array of size N X M with its main diagonal elements as 1's and 0's everywhere else.



In [81]:
N = int(input("your rows "))
M = int(input("your coloumns "))
np.eye(N,M)

your rows 3
your coloumns 4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

**Array Mathematics**:

ou are given two integer arrays, A and B of dimensions N X M.
Your task is to perform the following operations:

Add (A + B)
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )

In [1]:
import numpy as np
arr = []
arr2 = []
N = int(input("your rows "))
M = int(input("your coloumns "))
print("your first array is ")
for i in range(N):
    a =[] 
    for j in range(M):
         a.append(int(input())) 
    arr.append(a) 
print("your second array is ")
for i in range(N):
    b =[] 
    for j in range(M):
         b.append(int(input())) 
    arr2.append(b) 
arr = np.array(arr)
arr2 = np.array(arr2)
print(arr+arr2, arr-arr2, arr*arr2, arr//arr2, arr%arr2, arr**arr2, sep='\n')

your rows 1
your coloumns 4
your first array is 
1
2
4
3
your second array is 
5
6
7
8
[[ 6  8 11 11]]
[[-4 -4 -3 -5]]
[[ 5 12 28 24]]
[[0 0 0 0]]
[[1 2 4 3]]
[[    1    64 16384  6561]]


**Floor, Ceil and Rint**:

    ou are given a 1-D array,A . Your task is to print the floor,ceil  and  of all the elements of A.

In [6]:
import numpy as np
arr =[]
for i in range(9):
    arr.append(float(input("your array ")))
arr = np.array(arr)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

your array 1.1
your array 2.2
your array 3.3
your array 4.4
your array 5.5
your array 6.6
your array 7.7
your array 8.8
your array 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


**Sum and Prod**:

    You are given a 2-D array with dimensions N X M.
    Your task is to perform the sum tool over axis 0 and then find the product of that result.



In [12]:
import numpy as np
arr = []
N = int(input("your rows "))
M = int(input("your coloumns "))
print("your array is ")
for i in range(N):
    a =[] 
    for j in range(M):
         a.append(int(input())) 
    arr.append(a) 
arr = np.array(arr)
arr = np.sum(arr, axis = 0)
print(arr[0]*arr[1])

your rows 2
your coloumns 2
your array is 
1
2
3
4
24


**Min and Max**:

    You are given a 2-D array with dimensions N X M.
    Your task is to perform the min function over axis 1 and then find the max of that.

In [1]:
import numpy as np
arr = []
N = int(input("your rows "))
M = int(input("your coloumns "))
print("your array is ")
for i in range(N):
    a =[] 
    for j in range(M):
         a.append(int(input())) 
    arr.append(a) 
arr = np.array(arr)
arr = np.min(arr, axis = 1)
print ("is ",np.max(arr,axis=0))

your rows 4
your coloumns 2
your array is 
2
5
3
7
1
3
4
0
is  3


**Mean, Var, and Std**:

    ou are given a 2-D array of size N X M.
    Your task is to find:

    1-The mean along axis 1
    2-The var along axis 0
    3-The std along axis None

In [2]:
import numpy as np
arr = []
N = int(input("your rows "))
M = int(input("your coloumns "))
print("your array is ")
for i in range(N):
    a =[] 
    for j in range(M):
         a.append(int(input())) 
    arr.append(a) 
arr = np.array(arr)
print (np.mean(arr, axis = 1))
print (np.var(arr, axis = 0))
print (np.std(arr, axis = None))


your rows 2
your coloumns 2
your array is 
1
2
3
4
[1.5 3.5]
[1. 1.]
1.118033988749895


**Dot and Cross**:

    You are given two arrays A and B. Both have dimensions of N X M.
    Your task is to compute their matrix product.

In [ ]:
import numpy as np
arr = []
arr2 = []
N = int(input("your rows "))
print("your 1st array is ")
for i in range(N):
    a =[] 
    for j in range(N):
         a.append(int(input())) 
    arr.append(a) 
print("your 2sd array is ")
for i in range(N):
    b =[] 
    for j in range(N):
         a.append(int(input())) 
    arr.append(b) 
arr = np.array(arr)
arr2 = np.array(arr2)
print


## Thanks